name: Git checks
on: [pull_request]

jobs:
  git_checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"
          check-latest: true
          architecture: "x64"
      - name: Initialize project
        run: npm ci
      - name: Ensure linear git history
        run: git merge-base --is-ancestor "origin/${GITHUB_BASE_REF}" HEAD
      - name: Check for fixup or WIP commits
        run: |
          ! git log "origin/${GITHUB_BASE_REF}..HEAD" | egrep ' fixup! |wip|Wip|WIP'
